server:
  port: 9898
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/data/auth_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  application:
    name: AUTHENTICATION-SERVICE